### ISSUE TITLE
Issue with BMM_attention_model.py

### ISSUE THREAD

**Issue by brookefitzgerald** [dvatterott/BMM_attentional_CNN#1]
It seems like there's an error in your code. I copied and pasted the code of BMM_attention_model.py into a jupyter notebook to try it out and got the error message "Exception: Input 0 is incompatible with layer dense_2: expected shape=(None, 4), found shape=(None, 32)" caused by the line `find_att = dense_2a(conv_shape1)`.

Any thoughts?

![Photo of error](https://cloud.githubusercontent.com/assets/20567775/20969230/18a35594-bc56-11e6-99c6-973ccfb11524.png)

**Comment by dvatterott** [comment]
Hi Brooke,

There must have been a change in how keras specifies the shape of objects. I've played a little with this here at work, and was able to duplicate your error. 

I will try and give this some time tonight. I'll update everything once I get a fix. 

Another option is to use an older version of keras...which should work. 
Also, just to make sure we're on the same page. I was using the theano backend for keras when I wrote this. 

Dan

**Comment by dvatterott** [comment]
Another update. I've been looking at keras documentation... https://keras.io/layers/convolutional/
and I fixed the error on my end. It all stems from keras switching from a theano backend to tensorflow. 

I edited my keras.json file (https://keras.io/backend/) so that it looks like this:
{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}

Note the change to image_dim_ordering and backend.

These changes fixed things on my end. 

Let me know whether they fix things on your end. 

Dan

**Comment by TangShuangshuo** [comment]
I want to ask if the batch_size have to be setted to 1. If the batch_size is setted larger than 1,it will make a mistake at “conv_shape1“ because the size does not match, am I right?

**Comment by dvatterott** [comment]
You're correct. I explicitly programmed this so the batch size can only be one. I don't remember having a good reason for this so it's possible the code could be adapted for a different batch size.

**Comment by brookefitzgerald** [comment]
Hi Dan, 
Changing the keras.json solved the problem for me as well.
Thanks!
Brooke
