### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Zavianx** [dvatterott/BMM_attentional_CNN#4]
I have some question when i watch your model picture and yout code;
from your model picture,i see you apply the focused result to your conv2 and passing the focused result to the next conv3;
But from your code,you multiply the conv2 and conv1 result and pass it to the next conv3 instead of passing to conv2 .I'm confused about that.
I would appreciate it if you can answer my question,thank you

**Comment by dvatterott** [comment]
#3 please see your last issue
